swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Récupère toutes les transactions du mois en cours, groupées par compte
      description: Permet de visualiser toutes les transactions de l'utilisateur pour le mois actuel, groupées par compte.
      produces:
        - application/json
      responses:
        '200':
          description: Liste de transactions récupérée avec succès, groupée par compte
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '500':
          description: Erreur interne du serveur
  /user/profile/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Détails d'une transaction spécifique
      description: Permet de visualiser les détails d'une transaction en fournissant son identifiant.
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: Identifiant unique de la transaction
      produces:
        - application/json
      responses:
        '200':
          description: Détails de la transaction récupérés avec succès
          schema:
            $ref: '#/definitions/TransactionDetail'
        '404':
          description: Transaction non trouvée
        '500':
          description: Erreur interne du serveur
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Modifier les informations d'une transaction
      description: Permet de mettre à jour les informations d'une transaction spécifique.
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
          description: Identifiant unique de la transaction
        - in: body
          name: body
          description: Données à mettre à jour pour la transaction
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction mise à jour avec succès
        '400':
          description: Validation error in provided data
        '404':
          description: Transaction non trouvée
        '500':
          description: Erreur interne du serveur
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    type: object
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    type: object
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  Transaction:
    type: object
    properties:
      transactionId:
        type: string
        description: Identifiant unique de la transaction
      accountId:
        type: string
        description: Identifiant du compte associé
      date:
        type: string
        format: date
        description: Date de la transaction
      amount:
        type: number
        format: float
        description: Montant de la transaction
      category:
        type: string
        description: Catégorie de la transaction
      description:
        type: string
        description: Description de la transaction
  TransactionDetail:
    allOf:
      - $ref: '#/definitions/Transaction'
    properties:
      details:
        type: string
        description: Additional details about the transaction
  TransactionUpdate:
    type: object
    properties:
      amount:
        type: number
        format: float
        description: Nouveau montant de la transaction
      category:
        type: string
        description: Nouvelle catégorie de la transaction
      description:
        type: string
        description: Nouvelle description de la transaction  